services:
  mysql:
    image: mysql:9.3.0
    container_name: cm_mysql
    profiles:
      - mysql
      - db
      - all
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-root}'
      MYSQL_DATABASE: '${MYSQL_DATABASE:-my_database}'
      MYSQL_USER: '${MYSQL_USER:-my_user}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-my_password}'
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - db-mysql-volume:/var/lib/mysql
    networks:
      - app_net

volumes:
  db-mysql-volume:
