services:
  nginx:
    image: nginx
    container_name: symfony_nginx
    depends_on:
      - php-fpm
    volumes:
      - ../../app/:/app
      - ../../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../../log/nginx:/var/log/nginx
    ports:
      - "8080:80"
    networks:
      app_net:
